### ISSUE TITLE
 Crash after getsystem on Wind8.1 & Wind10 (not Wind7)

### ISSUE THREAD

**Issue by quentinhardy** [n1nj4sec/pupy#124]
Hello,

I have done some tests on **wind8.1 (x64)** and I have found a bug.
When you do a **_bypassuac_** and **after** a **_getsystem_** on the new session created by _bypassuac_, the remote process stops working.

**Notice:**
1. I have found this bug only on **wind8.1 (x64)**. On wind7 (x86 or x64), there is not this bug.
2. If I does a "_run as administrator_" on the pupy exe file and I do a _getsystem_ after, there is **not this bug** on wind8.1. Very strange ...

The bug is in the function **_GetTokenSid()_** in [security.py](https://github.com/n1nj4sec/pupy/blob/c67055d90f88d16662e7360644f04f4d1f96e018/pupy/packages/windows/all/pupwinutils/security.py).
These following lines crash the remote process:

```
[...]
r=windll.advapi32.GetTokenInformation(hToken, TokenUser, byref(TOKEN_USER()), 0, byref(dwSize))
    if r!=0:
        raise WinError()
    address = windll.kernel32.LocalAlloc(0x0040, dwSize)
    windll.advapi32.GetTokenInformation(hToken, TokenUser, address, dwSize, byref(dwSize))
    pToken_User = cast(address, POINTER(TOKEN_USER))
windll.advapi32.ConvertSidToStringSidA(pToken_User.contents.User.Sid, byref(pStringSid))
[...]
```

I'm sure that the problem occurs in the **_ConvertSidToStringSidA_** function:

```
windll.advapi32.ConvertSidToStringSidA(pToken_User.contents.User.Sid, byref(pStringSid))
```

This error occured the first time the **_GetTokenSid()_** function is used from **ListSids** function:

```
[...]
try:
                sids.append((pinfo['pid'], pinfo['name'], GetTokenSid(hToken), pinfo['username']))
except:
[...]
```

As soon as I have time, I will try to fix this bug...

**Comment by quentinhardy** [comment]
For information, the same error occurs on **wind10** (**x64**) after a _UAC bypass_ and _get system_: The remote process stops working.

```
>> info
hostname  : DESKTOP-X
[...]
release   : 10
version   : 10.0.10240
os_arch   : AMD64
proc_arch : 64bit
pid       : 1200
exec_path : C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe
[...]
uac_lvl   : 2/3
intgty_lvl: High
transport : ssl
launcher  : connect
>> run getsystem 
DEBUG:root:package psutil loaded on win_DESKTOP-X from path=packages/windows/amd64
DEBUG:root:package pupwinutils.security loaded on win_DESKTOP-X from path=packages/windows/all
```

**Comment by quentinhardy** [comment]
For information again, the same crash occures also when you do a "run as administrator" and after a _getsystem_ on wind10 (x64).

**Comment by AlessandroZ** [comment]
This error happens only when the process is launched from a ps1 file (ps1_oneliner or ps1). It crashes when "ConvertSidToStringSidA" is called : 

- [https://github.com/n1nj4sec/pupy/blob/89aa93532095d49bf3edef6cbf1d7f4edf8ac109/pupy/packages/windows/all/pupwinutils/security.py#L186](https://github.com/n1nj4sec/pupy/blob/89aa93532095d49bf3edef6cbf1d7f4edf8ac109/pupy/packages/windows/all/pupwinutils/security.py#L186)

I think, it's the same problem as we have since we work with powershell, it returns an "ERROR_NOT_ENOUGH_MEMORY" code error: 
- [https://msdn.microsoft.com/en-us/library/windows/desktop/aa376399(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa376399(v=vs.85).aspx)

It's weird because when you migrate to another process (you're not on a powershell process anymore), and try to list SID, the process crashes again. 

This powershell problem needs to be investigated.

**Comment by quentinhardy** [comment]
This bug seems fixed.
I have tested this module BypassUAC on wind10_**x64** from a **x32** process with **ps1_oneliner**. No problem anymore.
Notice from a **x64** process, the following message is printed:
```
OSError: Can't let you to do that because a well known bug is not fixed yet, migrate to a 32 bits process and run this action again.
Ex: run migrate -c 'C:\Windows\SysWOW64\notepad.exe'
```
Of course, not a problem -:)

I think this issue could be closed.
