### ISSUE TITLE
Library loading error

### ISSUE THREAD

**Issue by belko-letyago** [n1nj4sec/pupy#24]
When I am trying to run x86 payload on x64 system I see this error:
![error](https://cloud.githubusercontent.com/assets/3055972/10159996/caed27d4-66a3-11e5-9310-24dc75f9bcea.PNG)
But after closing this msgbox it is working fine:
```
macaddr   : xx:xx:xx:xx:xx:xx
pid       : 132
exec_path : C:\x86.exe
address   : 192.168.61.10
proc_arch : 32bit
hostname  : win7
os_arch   : AMD64
version   : 6.1.7601
release   : 7
```

**Comment by belko-letyago** [comment]
On another pc I get this error with x64 payload and x64 win7.

**Comment by n1nj4sec** [comment]
after some tests I did succeed reproducing this error and it seems to happen when the client connect for the first time and automatically import the python uuid module. I have however no clue why this pops up as msvcr90 should already be loaded.

**Comment by belko-letyago** [comment]
https://msdn.microsoft.com/en-us/library/ms235560(v=vs.90).aspx
MSDN says that this error happen when application is loading the C runtime library without using a manifest. Could you try to add manifest when building payloads?

**Comment by n1nj4sec** [comment]
unfortunately it is more complicated. You can't use a manifest with reflective DLL injection because it you would need to write both the manifest and the msvcr90.dll to the disk. Pupy loads the msvcr90 without a manifest file by handling windows contexts. The problem comes from the fact that the python uuid.py module manually reload the msvcr90 dll using ctypes whereas it already had been loaded from memory by pupy.
the uuid module does the following :
```
>>> ctypes.util.find_library('c')   
'msvcr90.dll'
>>> ctypes.CDLL('msvcr90.dll')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "ctypes\__init__.pyc", line 365, in __init__
WindowsError: [Error 1114] A dynamic link library (DLL) initialization routine failed
```
The quick fix would be to patch the uuid.py module but I'm wondering if patching the ctypes wouldn't be better as the problem would not appear again in another module

**Comment by n1nj4sec** [comment]
I think the bug is related to : https://bugs.python.org/issue17213

**Comment by n1nj4sec** [comment]
Could you tell me if the patch fixed the popups on the machines where you had the issue ? thank's

**Comment by belko-letyago** [comment]
Great! I don't see the popups anymore.
