### ISSUE TITLE
AttributeError: 'module' object has no attribute 'runLaZagne'

### ISSUE THREAD

**Issue by inside-shellshock** [n1nj4sec/pupy#309]
when i launch 'run lazagne' on a target computer with Windows 7 x64 pupy return me this error.
tryied to find a fix but nothing, anyone can help me?

**Comment by AlessandroZ** [comment]
In your title example, there is not space between "run" and "lazagne". So the module "runlazagne" is not present and it's normal. 

Type "run" and use the auto completion to write lazagne to be sure of the spelling.

**Comment by inside-shellshock** [comment]
>> run lazagne 
[-] 'module' object has no attribute 'runLaZagne'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\rpyc\core\protocol.py", line 305, in _dispatch_request
  File "C:\Python27\lib\site-packages\rpyc\core\protocol.py", line 541, in _handle_getattr
  File "C:\Python27\lib\site-packages\rpyc\core\protocol.py", line 507, in _access_attr
AttributeError: 'module' object has no attribute 'runLaZagne'

i have typed the "space" :')

**Comment by inside-shellshock** [comment]
Che poi possiamo anche parlare nella madrelingua.
UP UP!

**Comment by AlessandroZ** [comment]
Ahaha, I will continue in English to be understood by all. 

However, your problem is that you use an old version of lazagne. Now, lazagne use the runlazagne funciton (https://github.com/AlessandroZ/LaZagne/blob/master/Windows/laZagne.py#L217) that you should not have it on your pupy version. So Try, to upgrade the lazagne submodule or try to clone another time the pupy directory, it should fix your problem.

**Comment by inside-shellshock** [comment]
Alessà, i have cloned pupy again, update lazagne to the new version, but pupy gave me same error.
We should talk in PM 😭
