### ISSUE TITLE
Upgrading to Python3

### ISSUE THREAD

**Issue by rokups** [n1nj4sec/pupy#503]
Any thoughts on migrating to python3?

I did some R&D (inspired by pupy ofc) branded as [Launchpad](https://github.com/rokups/Launchpad) project (not actively developed because doing it alone is not motivating). What i achieved is running vanilla python3.6 from memory including native modules under windows xp and windows 10. Given that anything in-between is easily doable if it still does not work.

What would be implications for other platforms? Kivy i read was working on python3 support a while back.

What do you think?

**Comment by alxchk** [comment]
> Any thoughts on migrating to python3?

Yes, no way. It's more fat than python2 =\
Also no profit.

**Comment by rokups** [comment]
> It's more fat than python2

Citation needed. Besides they are both fat and at this point difference is negligible.

> Also no profit.

Proper unicode support and fstrings alone are great profit. How about language that is being maintained, bugs are being fixed and libraries for it being maintained? High profile projects are already dropping support for py2, it is the dead-end.

**Comment by alxchk** [comment]
> Citation needed.
I tried. You can try yourself and make measurements.

> Besides they are both fat and at this point difference is negligible.
Last year I tried to reduce memory consumption and fight for every megabyte. 

> Proper unicode support and fstrings alone are great profit.

Well, python3 add even more improvements than that, this is true. But it's more important for those "high profile projects". In fact most security scripts (which we try to adopt to pupy from time to time) is written for python2 only.  Even big ones like impacket. But impacket will be ported properly some time later, rest are very unlikely. We are not going to use pupy to run django, right?

If you take closer look on pupy, you'll find that large parts are written on ctypes, not python :) Rest is mostly workarounds and hacks (mostly because of RPyC). The code which is reliable mostly ugly. Maybe pupysh rewritten to the python3 can make sense, but python2 and python3 are incompatible when using rpyc. So.. Personally I don't see any reason to put tonns of efforts to migrate. If somebody do - he can try.

**Comment by cclauss** [comment]
```
>> [Python 3 is] more fat than python2

> Citation needed. Besides they are both fat and at this point difference is negligible.
```
"Python 3.6 is faster than any other Python version on many benchmarks." -- Victor Stinner
* https://us.pycon.org/2017/schedule/presentation/487

**Comment by fastchain** [comment]
@alxchk  thanks for an explanation. Are there any suggestions how to run python3 code in pupy?  :)

**Comment by alxchk** [comment]
Sure. Rewrite it to make compatible with python2 :]

**Comment by fastchain** [comment]
@alxchk  ![Roll-Safe-Think-About-It](https://user-images.githubusercontent.com/13186708/72784534-9e13a700-3c5b-11ea-8657-2f9e40bfb728.jpg)
