### ISSUE TITLE
[on_connect]: lazagne not working

### ISSUE THREAD

**Issue by rang0rn** [n1nj4sec/pupy#537]
If I try to run lazagne with the [on_connect] property in config, I get following error message:
[!] Error loading package Crypto.Math._Numbers_gmp (Crypto/Math/_Numbers_gmp.pyo pkg=False) : Traceback (most recent call last):
OSError: Cannot load library 'mpir'

I Installed gmpy2 with pip install gmpy2 and manually installed mpir.

If I run lazagne in pupyshell with run lazagne, the error doesn't show up and lazagne works as expected.

**Comment by AlessandroZ** [comment]
I have tested lazagne using the on_connect module and it works for me. However, you do not have the output printed on the screen that's why you may be confused. Credentials are stored directly on the database. You could see the content of the database as following: 
`>> creds`

To be sure, flush the database `>> creds -F` and run lazagne again, it should work.

**Comment by rang0rn** [comment]
Great, can be closed! Thanks!
