### ISSUE TITLE
Adding additional python modules to the client

### ISSUE THREAD

**Issue by msidagni** [n1nj4sec/pupy#54]
I am trying to add additional python modules to be integrated into the client. So far I figured that if I add an additional import to the "additional_imports.py" (for example import scapy) and in Windows I regenerate the library.zip using "build_library_helper.py", all the necessary pycs get included into the compressed library.zip. Then I generate the windows executable for the required architecture.

However, when I establish the connection between pupy client and server and then I run a pyshell, and I try to import the module, I receive an error saying "No module named X".

Are there any additional steps to be performed to include additional python modules into the library?

Is there any documentation on how pupygen.py actually work ?

Thanks.

Mike

**Comment by n1nj4sec** [comment]
To include additional python modules, just drop them in packages/windows/x86/ or packages/windows/x64/ and use load_package to load them from memory on a client. You don't need to edit the libraries included by default in the payloads.
It probably won't work as-is for scapy because scapy needs other dependencies like winpcap
Here is an example on how to include sqlite3 from memory : 
copy _sqlite3.pyd, sqlite3.dll and sqlite3 directory from C:\Python27\ of a windows install to packages/windows/x86 or packages/windows/x64 depending on your payload arch and then do :
```python
>> pupsrv.clients[0].load_package("_sqlite3") #load _sqlite3.pyd
True
>> pupsrv.clients[0].load_package("sqlite3") #load the package
True
>> pupsrv.clients[0].load_dll("packages/x86/sqlite3.dll") #load the dll wich sqlite3 needs to work
>> pupsrv.clients[0].conn.modules['_sqlite3']
<module '_sqlite3' from '<memimport>\_sqlite3.pyd'>
>> pupsrv.clients[0].conn.modules['sqlite3']
<module 'sqlite3' from '<memimport>\sqlite3\__init__.py'>
>> pupsrv.clients[0].conn.modules['sqlite3'].version
'2.6.0'
```
I hope it answer your question
