### ISSUE TITLE
Error in pupygen.py for exe_x64

### ISSUE THREAD

**Issue by msidagni** [n1nj4sec/pupy#55]
When I try to generate an exe_x64 client with pupygen.py with the command I get the following error:

python pupygen.py 172.16.72.171 -p 443 -t exe_x64 -o pupyx64.exe
Traceback (most recent call last):
  File "pupygen.py", line 90, in <module>
    w.write(binary)
TypeError: must be string or buffer, not tuple

This strangly does not happen if I try to generate an exe_x86 client

**Comment by n1nj4sec** [comment]
pupy is not in a stable version yet. Please look quickly at the code before asking things it's often quicker to look at the code rather than to post an issue on github ... https://github.com/n1nj4sec/pupy/blob/master/pupy/pupygen.py#L23 the parenthesis is not at it's place. It doesn't matter the pupygen.py has been totally rewritten in the dev branch so it will be fixed on it's own.
