### ISSUE TITLE
A silly question: what has Pupy Metasploit hasn't?

### ISSUE THREAD

**Issue by q2dg** [n1nj4sec/pupy#592]
I mean...I can't see on (on the other hand, very complete) Readme why I should try Pupy instead of (much more popular) Metasploit. If it could be explained many people would try Pupy, then. Thanks!

**Comment by HorneyAttorney** [comment]
Pupy injects payload shell directly into the memory.
"Pupy doesn't touch the disk ;)"

**Comment by q2dg** [comment]
Well, depending on the payload, metasploit neither...

**Comment by AlessandroZ** [comment]
Hi, 

This is an interesting question and I think everyone who uses pupy has its own reason. 

Metasploit is a great framework and I used a lot meterpreter but I cannot say how many remote shells I have lost doing a wrong command or because I opened a shell and the process crashes. This is not a problem when you have the exploit, you reproduce it again and you have another shell back, but sometimes you cannot lose it. 

I think one of the main work we try to do on this tool is to be really stable (it could crash of course) but you should try it and you will see that you will get your session for a while (it could happen that some modules fails but your session should still work). 

Then I would say that one different thing from the other RAT project is the interactive shell (even on Windows) that is really usefull when you're testing an internal network and you need to check some net commands (or others). You should run interactive commands (such as "runas") with a real prompt requesting for your password, you will have an history of your previous requests, you could do CTRL-C, you could use powershell to have the tab completion, etc. 

Then, you have lots of really great projects in python on github. Pupy could load these files remotely on memory in order to use these tools. For example, you could use impackets, lazagne, beroot, netcreds, etc. on your target without writing anything on the disk. I know that some tools are written in powershell and can be loaded on memory as well (for example, beroot is quite similar as powerup), but some tools doesn't exists in powershell. 

You have some other nice features such as loading a PE file in memory (such as mimikatz), and other modules like that. 

It's easy to debug because the stactrace is prompted and you should be able to understand the problem better. And for me, it was easier to debug than meterpreter because I prefer Python. 

Try both and you will see what you prefer.

**Comment by q2dg** [comment]
Oh, thanks a lot for your great explanation!
If you don't mind, I'll close the issue as solved,then
Thanks!
