### ISSUE TITLE
Create new repo with alxchk as maintainer.

### ISSUE THREAD

**Issue by Strazzom** [n1nj4sec/pupy#627]
@alxchk 
Given that the main project seems to be abandoned, I suggest duplicating the repository and renaming it to something indicative of progression (i.e. "pupy2"), and make yourself the official maintainer. You are basically filling that role anyway, so at this point it is just a matter of formality.

It is difficult for newcomers to figure out which is the most up to date branch of the project, creating needless headache for everyone.

As an aside, I would also recommend having two branches, (main and unstable) instead of just unstable, which is how you currently have it.

What do you think?

**Comment by p-l-** [comment]
@Strazzom @alxchk Unless you are granted the authorization by @n1nj4sec, please do not call your fork `pupy2` or anything with `pupy`. You can fork an open-source project, but you are not free to use its name.

**Comment by alxchk** [comment]
> What do you think?

Well, I don't see much reasons to do that. There is no much activity around the project anyway.

> I suggest duplicating the repository and renaming it to something indicative of progression (i.e. "pupy2")

1. To search for pupy2 you need to know that pupy2 exists. With github platform it was very easy to observe a progress in forks with "network" feature. Recently it became too many forks of pupy so this nice feature doesn't work anymore. Funny, but most of these forks are forks without own commits. 

2. Since you know that there is _a bit more alive (and no more than that)_ branch exists nobody prevents to use it. The nice example is rtl8812au driver, which have tons of forks which all are different and you can select something more appropriate for your usecase.

3. Branch was created a long time ago. From that time there are 0 issues and 0 pull requests which clearly shows no future of this initiative.

> It is difficult for newcomers to figure out which is the most up to date branch of the project, creating needless headache for everyone.

Maybe it's not that bad? Pupy is not well-known project like metasploit which everybody will say in some case - ah, this is just meterpreter.  Maybe it's better that the user of the project will know at least a little bit of what is he using, what is the story, how the thing works and what kind of help is required. For my opinion in case you are doing some pentest job you absolutely need to do this anyway. You can't afford to blindly trust the first thing you just cloned from the github. In the end you are going to apply this to your customer. 

> As an aside, I would also recommend having two branches, (main and unstable) instead of just unstable, which is how you currently have it.

I can change the name or add the branch but this will not change the content. To keep something stable during refactoring tests need to be created and some QA to be performed to check regressions and so on.

**Comment by Strazzom** [comment]
Noted.

> Branch was created a long time ago. From that time there are 0 issues and 0 pull requests which clearly shows no future of this initiative.

I disagree with this. First, it is impossible to open issues on your branch, seeing as it is a fork of the main branch. Perhaps I am mistaken, but I think you have to open issues on the main branch. This may be a misunderstanding of github on my part, but I think you might have issues if your fork allowed issues to be created. At the top of the screen, I see no "issues" tab.

Perhaps this is a configuration option?

Perhaps if it was enabled (supposing I am right), people would be inclined to submit pull requests to fix the issues reported.

**Comment by alxchk** [comment]
> At the top of the screen, I see no "issues" tab.
You are right. Either this was disabled by default or I disabled and forgot about that.

**Comment by Strazzom** [comment]
I see you have re-enabled it. Thank you.

**Comment by s1st3r** [comment]
@alxchk is doing a good job, @n1nj4sec got married he slowed down with devs, LOL! @alxchk can do wonders, even recreate the sources if he is good in C/C++

**Comment by n1nj4sec** [comment]
Hey guys !

I didn't got married but I do have a girlfriend and a life ;)

I don't have much free time to work on pupy and even less to read issues and answer to everyone.
However, I do use pupy at work when I have the occasion depending on the perimeter of the pentest I perform. During worktime I don't usually have time to improve pupy and I just "make things work" when I need them or find workarounds. The development in on hold for now but I count re-start working on it !
But seeing their good job and their implication if they agree I could add @alxchk and @AlessandroZ as collaborators of the project so we can all manage issues and merge pull requests on pupy. I could also make the master branch protected to force multiple people to review the code before merging our pull requests, so we can have a more stable code. What do you think ?

Cya,

Nicolas

**Comment by void-in** [comment]
@n1nj4sec Great to hear from you. And you deserve every bit of your family time since at the end that is what matters the most.

In Metasploit, we have this policy that the author of the PR never lands it to the master. We can follow the same procedure here as well. @alxchk and @AlessandroZ are both relatively active here so we can follow the same policy here as well. They both being the collaborators will lift off a lot of pressure from you as well. Provided they both agree to the proposal as well.

**Comment by AlessandroZ** [comment]
Hi guys, 

As I said to @n1nj4sec in private, he could add me as collaborator of the project. However, I'm like him, I could not spend all my free time working on it and answering issues. I'm totally agree to add @alxchk as collaborator, he's doing an amazing work, so it would be easier to push his commits without needed to do PRs. 

For the master branch protected to force multiple people to review the code, I think it could be possible. I used to review PRs to understand how the project evolve but I hope it will not add me too much extra work. 

However, the project is growing and PRs should be still accepted, otherwise the project cannot evolve. So if we are multiple collaborators, we could manage it easily.

**Comment by CG-root** [comment]
@alxchk , as a side note, it would be great if you can write short explanation in wiki on your fork on how to build it.

Additionally, it can be great if we can have an IRC channel so that people can ask questions or consult about pupy.

**Comment by Strazzom** [comment]
I might be willing to help with the more mundane maintenance tasks, such as maintaining the documentation. That is heavily dependent on whether I can make pupy generally useful though. I like the concept (python in-memory post exploitation framework), but I have some testing to do to see if I can make it work.

**Comment by b2az** [comment]
> It is difficult for newcomers to figure out...
... getting behind the architecture of pupy.

Feels like a never ending reverse engineering.
Will there be a Documentation in the future?

**Comment by alxchk** [comment]
> Will there be a Documentation in the future?

Without this request - very unlikely :) Maybe raise an issue and I will write some generic things to the wiki.
This is really unobvious thing.

**Comment by iNoSec** [comment]
Sorry for this stupid question but with all this fork and all this branch im lost in my choice... if i understand well the alpha must be the most up to date with all the alxchk and LaZagne change in their own repo?? i burn or im back with penguins?

**Comment by AlessandroZ** [comment]
No the main goal is still working on the same project. Right now the project is in "pause" because we haven't decided yet how we can manage it correctly. 

@alxchk, what do you thing about becoming a collaborator in order to be able to merge PRs. Because, in few weeks, I would like to do PRs as well but I won't do it to avoid conflicts. So we should find a solution.

**Comment by alxchk** [comment]
Well, we can try, why not. 

Actually right now pending PRs are not compatible with my branch (so with "alpha" here as well).

**Comment by AlessandroZ** [comment]
Great, that a good news ! :)

When you said "pending PRs" you talking about all PRs except yours (https://github.com/n1nj4sec/pupy/pull/594) ? If we accept your PR and then we will manage conflicts on others, it should be ok or even your PR is out of date comparing to your fork?

**Comment by alxchk** [comment]
My branch is not synced to the head of current unstable branch, it's actually 7 commits behind. This is not that bad, but I need to review what is missing. Likely merge will not be hard. But there are some large PRs which also changed a lot of things, like https://github.com/n1nj4sec/pupy/pull/568. Likely compatible commits should be cherry-picked, without full merge. Also I  cherry-picked some fixes from other PRs some time ago, like https://github.com/alxchk/pupy/commit/2f2bab378e613f6443aed3d74f510ffb8e0ee03d

**Comment by AlessandroZ** [comment]
Do not hesitate to merge your PR when you think it's ok, we will close PRs that you already embed into yours and for big PRs, like #568, I will check with @quentinhardy to find a way to resolve conflicts. :+1:

**Comment by Strazzom** [comment]
Where did we leave off with this? I gather that there will be some work required to merge the branches, but at the very least, could you allow @alxchk and @AlessandroZ to commit to main, @n1nj4sec?

I propose--until the branches can be merged--that all of @alxchk's work be moved to an "unstable" branch on the main repo. It would at least make it easier for me, because I can't commit to alxchk's repo, and even if I could, it makes no sense to do so if I could be using this one.

**Comment by AlessandroZ** [comment]
@n1nj4sec already gave me access to merge PRs, and I suppose @alxchk have access too. 
I was waiting @alxchk to merge his own PR when he was ready and then we will manage other PRs. Until that, I'm blocked too.

**Comment by alxchk** [comment]
I merged what I can. Result should work but tests needed. I also started to write some notes about pupy. WIP, but better than nothing.

https://github.com/n1nj4sec/pupy/blob/unstable/pupy/DEVELOPMENT.md

**Comment by AlessandroZ** [comment]
Awesome work !!!! Thanks a lot
👍

**Comment by quentinhardy** [comment]
Thank-you very much @alxchk.

**Comment by Strazzom** [comment]
I am going to close this, seeing as we got the project rolling again.
