### ISSUE TITLE
[Request] Auto run module after got session

### ISSUE THREAD

**Issue by j3ssie** [n1nj4sec/pupy#674]
First of all pupy is a great tool.
I just wonder is there anyway to auto run some module after I got new session.

**Comment by alxchk** [comment]
There are two types of "autorun".

1. scriptlets - embedded to client during generation. This thing executed independently of connection to the pupysh.
2. event handlers. Once client connected to pupysh, pupysh fires `on_connect` event. To run command on this event you should add to config something like this:

```
> config on_connect my_nice_client ls
```

where `my_nice_client` is either `tag` or `node` or any other filter. To run something on every client you can use `any`. Instead of command you can also use `include:section_name` statement. This can be found from PupyTriggers.py

**Comment by j3ssie** [comment]
very clear thanks you.
