### ISSUE TITLE
keylogger error

### ISSUE THREAD

**Issue by tanujain** [n1nj4sec/pupy#686]
When I try to run gather/keylogger start, it gives "local variable r referenced before assignment error".
![whatsapp image 2018-10-05 at 3 53 59 pm](https://user-images.githubusercontent.com/2994184/46563566-0b5cc680-c8b7-11e8-89c8-89e551127705.jpeg)

**Comment by tanujain** [comment]
ok for mac it's not implemented.

**Comment by Strazzom** [comment]
@alxchk: This actually should work... Not sure why it doesn't. Is the keylogger platform specific? Does OSX implement keyboard input differently than other Unix OSes?

**Comment by alxchk** [comment]
Sure. Windows version uses hooks/win api, linux - xorg xinput2. One for macos should use their api

**Comment by Strazzom** [comment]
It might be a good idea to implement this at some point. It is a pretty simple feature, not sure how hard it would be on Mac though. May take a look at this if I get a chance.

**Comment by alxchk** [comment]
Besides keylogger, pupy on Mac is in very early and bad shape. 
1. Native client required, or better extended python version (with support for loading plugins from memory), because python2.7 still there by default.
2. Basic components should be fixed, like psutil.

There is reeealy big amount of work todo, keylogger do have very low priority.
