### ISSUE TITLE
Update Installation Page on Wiki

### ISSUE THREAD

**Issue by gitcl0ne** [n1nj4sec/pupy#863]
I have spent 8 hours straight trying to download this tool.  I am beyond upset, I am simply trying to install the tool for a final presentation for a college malware course.  "python create-workspace.py -DG pupyws" on the wiki returns: "create-workspace.py: error: unrecognized arguments: -DG"  I then try to install using virtualenv flag and get error: "python create-workspace.py -E virtualenv pupws
[+] Git repo at /root/attack/tools/pupy
Docker either is not installed or not configured.
Installation: https://docs.docker.com/install/"  Why is the tool throwing a docker error if I am attempting to install the tool in a virtualenv?  This tool is broken and garbage.  The authors suck.

**Comment by Silver15987** [comment]
Hey! Maybe if you can send the problem in detail, a solution can be found.

**Comment by pantharshit00** [comment]
> The authors suck

Well first of all, stop acting entitled here. The author of this project doesn't owe you anything. If you feel this library sucks, feel free to write your own.


Now back to your problem, the wiki clearly mentions it is recommended to use docker here. If you can't use that at least post some useful details in the issue like screenshots of error messages, instead of ranting on the author and this library. If you can't provide the error screen, it is very hard for anyone to help you.


So revalue and stop being entitled

**Comment by gitcl0ne** [comment]
The error messages are in quotes.  The installation script create_workspace.py is broken.  The -E command line argument is confused with a docker although my command specifically states to install to a virtualenv.  alxchk's installation page on the Wiki stated to run `python` create-workspace.py -DG pupyws" for a light install which returned "create-workspace.py: error: unrecognized arguments: -DG"  And it doesn't work, clone this exact repo right now and try for yourself.  Which is exactly why alxchk deleted the instructions from the Installation page just today, because I am right.  The installation script is broken, accept the issues with the code, people have a right to be upset when you've wasted their time.  I'm not a toddler and don't need the lecture.

**Comment by gitcl0ne** [comment]
Check the last edit to the installation wiki.  alxchk edited and deleted the segment of code today because it is broken.  Do a little more research before you fly off the handle, buddy.

**Comment by gitcl0ne** [comment]
And I have watched multiple YouTube videos where both of those commands work.  The user is supposed to be greeted with `[+] Creating virtualenv` seen it countless times.

**Comment by alxchk** [comment]
Some time ago (> 2 years ago) -DG downloaded precompiled templates. This was for n1nj4sec repo only. At some point things to stop worked properly, and to avoid mess, I removed this. Anyway, I can't manage releases for this repo even I want (but I don't want). Also I don't want to mess with binary releases. Templates compilation take some time, but usually need to be done once.

About documentation - you are right. It's outdated. If you want, you may update it.

**Comment by gitcl0ne** [comment]
What I want is the command for how to get a working install on my machine, without error.  Do you have this command? Or is this tool not able to be installed?

**Comment by alxchk** [comment]
Well, you need to have at least configured docker, which you are able to control from your current user, and maybe python2 with pip, virtualenv and other dependencies at host machine. If you'll check `./create-workspace.py --help` you may find options which fits your system better. You may try something like `./create-workspace.py -E docker /some/path/to/workdir` first.

From time to time compilation/deployment breaks, because of upstream python packages updates. That is life )

**Comment by gitcl0ne** [comment]
I pulled and ran your unstable docker and is difficult to get tool to communicate with other machine's.  Networking would be easier for me directly on my machine.  Seems like I won't be getting an install it sounds.  Thank you anyway, good luck with this project.
