### ISSUE TITLE
Provide capability to interact with a specific client

### ISSUE THREAD

**Issue by artagel** [n1nj4sec/pupy#9]
Like meterpreter, it would be useful to be able to interact with one client at a time, or all as it's implemented now.  
The only way to do that now is with a -f filter of a computer name, or some other regex.  Doing so by ID number would be helpful.

**Comment by byt3bl33d3r** [comment]
@artagel agreed, @n1nj4sec I think it would be best to make the pupy shell commands as close as possible to metasploit so that it's instantly familiar  to everyone (e.g. ```clients``` would be ```sessions``` etc...)

**Comment by artagel** [comment]
It does look like -f <id> will work.  But yes, I believe being more like meterpreter will lower the learning curve and let people transfer between frameworks easily.

**Comment by n1nj4sec** [comment]
yea I planned to implement a default filter to avoid typing -f <id> each time. A little like the sessions -i of meterpreter. For s/clients/sessions why not

**Comment by n1nj4sec** [comment]
ok, clients aliased to sessions to be more instinctive (I didn't remove "clients" because I don't have the time to take new screenshots :p) and sessions have the -i option to set a global filter for all further commands. for example :
```
sessions -i 1
```
will change the global filter and the next commands will not be dispatched everywhere. It should be easier not to forgot a -f :-)
